services:
  - type: web
    name: proad
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
